namespace: konaai-dev  # Change to "default" if you're moving everything there
deployment:
  name: konaai-dev-api
replicaCount: 1
image:
  repository: us-central1-docker.pkg.dev/konaai-dev-462909/konaai-gke/dev-api
  tag: latest
  pullPolicy: IfNotPresent
container:
  name: api-container
  port: 80
service:
  name: api-service
  type: ClusterIP
  port: 80
  targetPort: 80
resources:
  requests:
    memory: "128Mi"
    cpu: "70m"
  limits:
    memory: "128Mi"
    cpu: "300m"
labels:
  app: api-app
  
autoscaling:
  enabled: true       # set true if you want HPA
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
serviceAccount:
  create: false
ingress:
  enabled: false

      
