name: 'Build and Deploy to GKE'

on:
  workflow_dispatch:

jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      # Step 1: Checkout code
      - name: 'Checkout'
        uses: actions/checkout@v4

      # Step 2: Authenticate to Google Cloud
      - name: Set up Google Cloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_LOGIN_SERVER }}

      # Step 3: Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
         gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      # Step 4: Build and push Docker image
      - name: 'Build and push Docker container'
        run: |
          IMAGE=us-central1-docker.pkg.dev/konaai-dev-462909/konaai-gke/dev-api
          docker build -f KonaAI.Master/KonaAI.Master.API/Dockerfile -t $IMAGE:${{ github.sha }} .
          docker push $IMAGE:${{ github.sha }}

          # Optional: also push "latest" tag
          docker tag $IMAGE:${{ github.sha }} $IMAGE:latest
          docker push $IMAGE:latest
                   
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
         cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
         location: ${{ secrets.GKE_LOCATION }}
         project_id: ${{ secrets.GKE_PROJECT }}

      - name: Deploy to GKE with manifests
        run: |
           #kubectl apply -f OrgKonaAI/kubernetes-manifests/cert-manager.yaml 
           #kubectl apply -f Deployments/Env-Variables/ui-var.yaml
           kubectl apply -f KonaAI.Master/kubernetes-manifests/Deployment.yaml
           #kubectl rollout restart deployment ui-deployment
           #kubectl rollout status deployment/ui-deployment
           #kubectl apply -f KonaAI.Master/kubernetes-manifests/API-Ingress.yaml
